### ISSUE TITLE
Doesn't compile with GCC 8.1+

### ISSUE THREAD

**Issue by Coffei** [silviucpp/epqueue#2]
Hi,
we are using this lib in our Elixir project and the dependency doesn't compile since GCC 8.1. I get the following error when compiling the lib. 
Previously I was downgrading gcc to older versions, but this workaround is getting less and less convenient as GCC 8.2 is now the default in Fedora 29 (which I use).

Any chance for a fix?

```
===> Compiling epqueue
make: Entering directory '/home/xxx/workspace/yyy/deps/epqueue/c_src'
 CPP    epqueue.cc
In file included from /usr/local/lib/erlang/erts-10.0.2/include/erl_nif.h:306,
                 from /home/xxx/workspace/yyy/deps/epqueue/c_src/epqueue.h:4,
                 from /home/xxx/workspace/yyy/deps/epqueue/c_src/epqueue.cc:1:
/home/xxx/workspace/yyy/deps/epqueue/c_src/epqueue.cc: In function ‘bool is_owner(ErlNifEnv*, epqueue*)’:
/usr/local/lib/erlang/erts-10.0.2/include/erl_nif_api_funcs.h:625:79: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
 #  define enif_make_pid(ENV, PID) ((void)(ENV),(const ERL_NIF_TERM)((PID)->pid))
                                                                               ^
/home/xxx/workspace/yyy/deps/epqueue/c_src/epqueue.cc:59:66: note: in expansion of macro ‘enif_make_pid’
     if(enif_self(env, &self) && !enif_is_identical(q->owner_pid, enif_make_pid(env, &self)))
                                                                  ^~~~~~~~~~~~~
/home/xxx/workspace/yyy/deps/epqueue/c_src/epqueue.cc: In function ‘ERL_NIF_TERM nif_epqueue_new(ErlNifEnv*, int, const ERL_NIF_TERM*)’:
/usr/local/lib/erlang/erts-10.0.2/include/erl_nif_api_funcs.h:625:79: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
 #  define enif_make_pid(ENV, PID) ((void)(ENV),(const ERL_NIF_TERM)((PID)->pid))
                                                                               ^
/home/xxx/workspace/yyy/deps/epqueue/c_src/epqueue.cc:110:28: note: in expansion of macro ‘enif_make_pid’
         qinst->owner_pid = enif_make_pid(env, &self);
                            ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [nif.mk:78: /home/xxx/workspace/yyy/deps/epqueue/c_src/epqueue.o] Error 1
make: Leaving directory '/home/xxx/workspace/yyy/deps/epqueue/c_src'
===> Hook for compile failed!
```

**Comment by silviucpp** [comment]
Can you please try and see if appending `-Wno-ignored-qualifiers` to the line : https://github.com/silviucpp/epqueue/blob/master/c_src/Makefile#L38 will solve your issues ?

**Comment by Coffei** [comment]
Yes, that fixes the issue, with that switch added it compiles successfully without any warnings. I meanwhile upgraded to GCC 9.1.1, but the symptoms are the same.

**Comment by silviucpp** [comment]
-Wno-ignored-qualifiers fixes as well GCC 9.1.1 ? if yes can you please send a pull request ?

Silviu

**Comment by Coffei** [comment]
Yeah, I am on GCC 9.1.1 now and the flag fixes it. I'll see if I can test on GCC 8.x and will make a PR. Thanks!

**Comment by silviucpp** [comment]
Thanks !
